### ISSUE TITLE
Stop on MultiExiftool.Executable.parse_errors

### ISSUE THREAD

**Issue by fitmap** [janfri/multi_exiftool#16] opened 2024-05-04 07:59 UTC
I wrote a patch, then it works, but I do not known why.

module MultiExiftool
	# Mixin for Reader and Writer.
	module Executable
		def parse_errors
			if @stderr.stat.size.zero?
				@errors = []
			else
				@errors = @stderr.read.lines(chomp: true).select {|l| l =~ /^(Error|Warning):/}
			end
		end
	end
end

**Comment by janfri** [comment] 2024-05-04 13:25
Strange. Which operation system do you use? Could you post a code example, which shows this behaviour?

**Comment by janfri** [comment] 2024-05-10 11:44
I close this issue because I could not reproduce the problem. Feel free to reopen it if you have more information.

**Comment by janfri** [comment] 2024-05-23 18:46
Maybe it's the same problem as #17

**Comment by janfri** [comment] 2024-05-23 19:30
I hope it's fixed in multi_exiftool version 0.18.1. Let me know if it works for you.

**Closed as completed** 2024-05-31 20:42 UTC
